# Default state for all rules.
default: true

# Path to configuration file to extend.
extends: null

# Inconsistent indentation for list items at the same level.
MD005: false

# Unordered list indentation.
MD007: false

# Line length.
MD013:
    line_length: 120
    code_blocks: false

# Inline HTML.
MD033: false

# Blank line inside blockquote
MD028: false

# Bare URL used
MD034: false
