extends: default

ignore: |
    build/
    dist/
    node_modules/

rules:
    braces:
        level: warning
        max-spaces-inside: 1
    brackets:
        level: warning
        max-spaces-inside: 1
    comments: disable
    comments-indentation: disable
    document-start: disable
    empty-lines:
        max: 1
        max-start: 0
        max-end: 0
    line-length: disable
    truthy:
        allowed-values:
            - 'true'
            - 'false'
        check-keys: false
